apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-sparse-pool
  annotations:
    cas.openebs.io/create-pool-template: cstor-pool-create-custom-0.8.0
    cas.openebs.io/config: |
      #For default sparse pool set the limit at 2Gi to safegaurd 
      # cstor pool from consuming more memory and causing the node 
      # to get into memory pressure condition. By default K8s will set the 
      # Requests to the same value as Limits. For example, when Limit is
      # set to 2Gi, the pool could get stuck in pending schedule state,
      # if node doesn't have Requested (2Gi) memory. 
      # Hence setting the Requests to a minimum (0.5Gi). 
      - name: PoolResourceRequests
        value: |-
            memory: 0.5Gi
            cpu: 100m
      - name: PoolResourceLimits
        value: |-
            memory: 2Gi
            cpu: 500m
      # Put your required tolerations here
      # The key in tolerations ( e.g. t1, t2 ) cannot be same for different tolerations
      - name: Tolerations
        value: |-
          t1:
            effect: NoSchedule
            key: testExists
            operator: Exists
          t2:
            effect: NoSchedule
            key: testEqual
            operator: Equal
            value: "testEuqalValue"
      #- name: AuxResourceLimits
      #  value: |-
      #      memory: 1Gi
      #      cpu: 100m
spec:
  name: cstor-sparse-pool
  type: sparse
  maxPools: 3
  poolSpec:
    poolType: striped
