apiVersion: openebs.io/v1alpha1
kind: CASTemplate
metadata:
  name: cast-standard-cstorpool-0.6.0
spec:
  # A list of deafult configs can be entered here to utilise it in run tasks.
  defaultConfig:
  # cstorpool is the container which runs zpool replication controller and communicates with iscsi target.
  - name: CstorPoolImage
    value: openebs/cstor-pool:ci
  # cstor-pool-mgmt is the container which watches for cstorpool and cstorvolumereplica CRs and runs the pool and volumereplica related operations like create, delete, import, etc.
  - name: CstorPoolMgmtImage
    value: openebs/cstor-pool-mgmt:cstor-feature-integration-ci
  # A hostPath volume mounts a file or directory from the host node’s filesystem into your Pod.
  # 'DirectoryOrCreate' value  ensures nothing exists at the given path, an empty directory will be created
  - name: hostPathType
    value: DirectoryOrCreate
    # This is the namespace where namespaced resources related to pool will be deleted.
  - name: runNamespace
    value: openebs
  taskNamespace: openebs
  run:
    tasks:
    # Following are the list of run tasks that are executed in order to create a storage pool
    - cstor-pool-create-list-disk-0.6.0
    - cstor-pool-create-list-node-0.6.0
    - cstor-pool-create-put-cr-0.6.0
    - cstor-pool-create-put-deployment-0.6.0
    - cstor-pool-create-put-storagepool-0.6.0
    - cstor-pool-create-patch-spc-0.6.0
