apiVersion: openebs.io/v1alpha1
kind: CASTemplate
metadata:
  name: cstor-pool-delete-cast
spec:
  # A list of deafult configs can be entered here to utilise it in run tasks.
  defaultConfig:
    # This is the namespace where namespaced resources related to pool creation will be created.
  - name: runNamespace
    value: openebs
  taskNamespace: openebs
  run:
    tasks:
    # Following are run tasks that are executed in order to delete a storage pool
    - cstor-pool-delete-listcsp-0.6.0
    - cstor-pool-delete-delete-csp-0.6.0
    - cstor-pool-delete-list-deploy-0.6.0
    - cstor-pool-delete-delete-deploy-0.6.0
    - cstor-pool-delete-listsp-0.6.0
    - cstor-pool-delete-delete-storagepool-0.6.0
