# This run task lists all cstor pool CRs that need to be deleted
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-listcsp-0.6.0
  namespace: openebs
data:
  meta: |
    id: deletelistcsp
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    action: list
    options: |-
      labelSelector: openebs.io/storagepoolclaim={{.CstorPool.owner}}
  post: |
    {{- $csps := jsonpath .JsonResult `{range .items[*]}pkey=csps,{@.metadata.name}=;{end}` | trim | default "" | splitList ";" -}}
    {{- $csps | notFoundErr "cstor pool cr not found" | saveIf "deletelistcsp.notFoundErr" .TaskResult | noop -}}
    {{- $csps | keyMap "csplist" .ListItems | noop -}}
---
# This run task delete all the required cstor pool CR
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-delete-csp-0.6.0
  namespace: openebs
data:
  meta: |
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    action: delete
    id: deletecstorpoolcr
    objectName: {{ keys .ListItems.csplist.csps | join "," }}
---
# This run task lists all the required cstor pool deployments that need to be deleted
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-list-deploy-0.6.0
  namespace: openebs
data:
  meta: |
    id: cstorpoollistdeploy
    apiVersion: extensions/v1beta1
    runNamespace: openebs
    kind: Deployment
    action: list
    options: |-
      labelSelector: openebs.io/storagepoolclaim={{.CstorPool.owner}}
  post: |
    {{- $csds := jsonpath .JsonResult `{range .items[*]}pkey=csds,{@.metadata.name}=;{end}` | trim | default "" | splitList ";" -}}
    {{- $csds | notFoundErr "cstor pool deployment not found" | saveIf "cstorpoollistdeploy.notFoundErr" .TaskResult | noop -}}
    {{- $csds | keyMap "csdlist" .ListItems | noop -}}
---
# This run task deletes all the required cstor pool deployments
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-delete-deploy-0.6.0
  namespace: openebs
data:
  meta: |
    id: cstorpooldeletedeploy
    runNamespace: openebs
    apiVersion: extensions/v1beta1
    kind: Deployment
    action: delete
    objectName: {{ keys .ListItems.csdlist.csds | join "," }}
---
# This run task lists all storage pool CRs that need to be deleted
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-listsp-0.6.0
  namespace: openebs
data:
  meta: |
    id: deletelistsp
    apiVersion: openebs.io/v1alpha1
    kind: StoragePool
    action: list
    options: |-
      labelSelector: openebs.io/storagepoolclaim={{.CstorPool.owner}}
  post: |
    {{- $sps := jsonpath .JsonResult `{range .items[*]}pkey=sps,{@.metadata.name}="";{end}` | trim | default "" | splitList ";" -}}
    {{- $sps | notFoundErr "storge pool cr not found" | saveIf "deletelistcsp.notFoundErr" .TaskResult | noop -}}
    {{- $sps | keyMap "splist" .ListItems | noop -}}
---
# This run task deletes the required storage pool claim object
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-delete-storagepool-0.6.0
  namespace: openebs
data:
  meta: |
    id: cstorpooldeletestoragepool
    apiVersion: openebs.io/v1alpha1
    kind: StoragePool
    action: delete
    objectName: {{ keys .ListItems.splist.sps | join "," }}
