apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-listcsp-0.6.0
  namespace: default
data:
  meta: |
    id: deletelistcsp
    apiVersion: openebs.io/v1alpha1
    runNamespace: default
    kind: CStorPool
    action: list
    options: |-
      labelSelector: cas.openebs.io/storage-pool-claim={{.CstorPool.owner}}
    retry: "10,30s"
  post: |
    {{- $csps := jsonpath .JsonResult `{range .items[*]}pkey=csps {@.metadata.name}="";{end}` | trim | default "" | splitList ";" -}}
    {{- $csps | notFoundErr "cstor pool cr not found" | saveIf "deletelistcsp.notFoundErr" .TaskResult | noop -}}
    {{- $csps | asKeyMap "csplist" .ListItems | noop -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-delete-csp-0.6.0
  namespace: default
data:
  meta: |
    apiVersion: openebs.io/v1alpha1
    runNamespace: default
    kind: CStorPool
    action: delete
    id: deletecstorpoolcr
    objectName: {{ keys .ListItems.csplist.csps | join "," }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-list-deploy-0.6.0
  namespace: default
data:
  meta: |
    id: cstorpoollistdeploy
    apiVersion: extensions/v1beta1 
    runNamespace: default
    kind: Deployment
    action: list
    options: |-
      labelSelector: cas.openebs.io/storage-pool-claim={{.CstorPool.owner}}
    retry: "10,30s"
  post: |
    {{- $csds := jsonpath .JsonResult `{range .items[*]}pkey=csds {@.metadata.name}="";{end}` | trim | default "" | splitList ";" -}}
    {{- $csds | notFoundErr "cstor pool deployment not found" | saveIf "cstorpoollistdeploy.notFoundErr" .TaskResult | noop -}}
    {{- $csds | asKeyMap "csdlist" .ListItems | noop -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-delete-deploy-0.6.0
  namespace: default
data:
  meta: |
    id: cstorpooldeletedeploy
    runNamespace: default
    apiVersion: extensions/v1beta1
    kind: Deployment
    action: delete
    objectName: {{ keys .ListItems.csdlist.csds | join "," }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-delete-delete-storagepool-0.6.0
  namespace: default
data:
  meta: |
    id: cstorpooldeletestoragepool
    runNamespace: default
    apiVersion: openebs.io/v1alpha1
    kind: StoragePool
    action: delete
    objectName: storage{{.CstorPool.owner}}
