apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-list-disk-0.6.0
  namespace: default
data:
  meta: |
    id: cstorpoollistdisk
    apiVersion: openebs.io/v1alpha1
    kind: StoragePoolClaim
    objectName: {{.CstorPool.spc}}
    action: get
  post: |
    {{- jsonpath .JsonResult "{range .spec.disks.diskList[*]}{$},{end}" | trim | saveAs "cstorpoollistdisk.disk" .TaskResult | noop -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-list-node-0.6.0
  namespace: default
data:
  meta: |
    id: cstorpoollistnode
    apiVersion: openebs.io/v1alpha1
    kind: Disk
    action: get
    repeatWith:
      kind: name
      resources:
        {{- $diskList := .TaskResult.cstorpoollistdisk.disk | replace "," " "| trim | split " "}}
        {{ range $k,$v := $diskList }}
        - {{$v}}
        {{ end }}
  post: |
    {{- $nodesList := jsonpath .JsonResult `pkey=nodes,{@.metadata.labels.kubernetes\.io/hostname}={@.spec.path};` | trim | default "" | splitList ";" -}}
    {{- $nodesList | keyMap "cstorNodePoolList" .ListItems | noop -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-put-cr-0.6.0
  namespace: default
data:
  meta: |
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    action: put
    id: createputcstorpool
    repeatWith:
      resources:
        {{- range $k, $v := .ListItems.cstorNodePoolList.nodes}}
        - {{ $k }}
        {{- end }}
  post: |
    {{- jsonpath .JsonResult `{.metadata.name}` | trim | saveAs "createputcstorpool.objectName" .TaskResult | noop -}}
    {{- $nodeUidMap := jsonpath .JsonResult `pkey=nodesUid,{.metadata.labels.kubernetes\.io/hostname}={.metadata.uid};` | trim | default "" | splitList ";" -}}
    {{- $nodeUidMap | keyMap "cstorNodeUidList" .ListItems | noop -}}
  task: |
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    metadata:
      name: {{.CstorPool.owner}}-{{ .ListItems.currentRepeatResource}}
      labels:
        cas.openebs.io/storage-pool-claim: {{.CstorPool.spc}}
        kubernetes.io/hostname: {{ .ListItems.currentRepeatResource }}
    spec:
      disks:
        diskList: {{ pluck .ListItems.currentRepeatResource .ListItems.cstorNodePoolList.nodes }}
      poolSpec:
        poolType: {{.CstorPool.poolType}}
        cacheFile: /tmp/{{.CstorPool.spc}}.cache
        overProvisioning: false
    status:
      phase: {{ .CstorPool.phase }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-put-deployment-0.6.0
  namespace: default
data:
  meta: |
    runNamespace: default
    apiVersion: extensions/v1beta1
    kind: Deployment
    action: put
    id: cstorpoolcreatedeploy
    repeatWith:
      resources:
      {{- range $k, $v := .ListItems.cstorNodeUidList.nodesUid }}
      - {{ $k }}
      {{- end }}
  post: |
    {{- jsonpath .JsonResult `{.metadata.name}` | trim | saveAs "cstorpoolcreatedeploy.objectName" .TaskResult | noop -}}
  task: |
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: cstor-pool-deploy-{{ .ListItems.currentRepeatResource}}
      labels:
        cas.openebs.io/storage-pool-claim: {{.CstorPool.owner}}
        app: cstor-pool
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: cstor-pool
      template:
        metadata:
          labels:
            app: cstor-pool
        spec:
          serviceAccountName: openebs-maya-operator
          nodeSelector:
            kubernetes.io/hostname: {{ .ListItems.currentRepeatResource}}
          containers:
          - name: cstor-pool
            # The image name here will be changed to openebs once the business logic pr is reviewed and merged in openebs/maya.
            image: {{ .Config.CstorPoolImage.value }}
            ports:
            - containerPort: 12000
              protocol: TCP
            - containerPort: 3233
              protocol: TCP
            - containerPort: 3232
              protocol: TCP
            securityContext:
              privileged: true
            volumeMounts:
            - name: device
              mountPath: /dev
            - name: tmp
              mountPath: /tmp
            - name: udev
              mountPath: /run/udev
              # To avoid clash between terminating and restarting pod in case older zrepl gets deleted faster, we keep initial delay.
            lifecycle:
              postStart:
                 exec:
                    command: ["/bin/sh", "-c", "sleep 2"]
          - name:    cstor-pool-mgmt
            # The image name here will be changed to openebs once the business logic pr is reviewed and merged in openebs/maya.
            image: {{ .Config.CstorPoolMgmtImage.value }}
            ports:
            - containerPort: 9500
              protocol: TCP
            securityContext:
              privileged: true
            volumeMounts:
            - name: device
              mountPath: /dev
            - name: tmp
              mountPath: /tmp
            - name: udev
              mountPath: /run/udev
            env:
              # OPENEBS_IO_CSTOR_ID env has UID of cStorPool CR.
            - name: OPENEBS_IO_CSTOR_ID
              value: {{ pluck .ListItems.currentRepeatResource .ListItems.cstorNodeUidList.nodesUid |first }}
          volumes:
          - name: device
            hostPath:
              # directory location on host
              path: /dev
              # this field is optional
              type: Directory
          - name: tmp
            hostPath:
              # From host, dir called /var/openebs/shared-<uid> is created to avoid clash if two replicas run on same node.
              path: /var/openebs/shared-a2b
              type: {{ .Config.hostPathType.value }}
          - name: udev
            hostPath:
              path: /run/udev
              type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-patch-spc-0.6.0
  namespace: default
data:
  meta: |
    id: createpatchspc
    apiVersion: openebs.io/v1alpha1
    kind: StoragePoolClaim
    objectName: {{.CstorPool.owner}}
    action: patch
  task: |
    type: merge
    pspec: |-
      status:
        phase: online
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-put-storagepool-0.6.0
  namespace: default
data:
  meta: |
    apiVersion: openebs.io/v1alpha1
    kind: StoragePool
    action: put
    id: createputstoragepool
    repeatWith:
      resources:
        {{- range $k, $v := .ListItems.cstorNodePoolList.nodes}}
        - {{ $k }}
        {{- end }}
  post: |
    {{- jsonpath .JsonResult `{.metadata.name}` | trim | saveAs "createputstoragepool.objectName" .TaskResult | noop -}}
  task: |
    {{- $diskList := .TaskResult.cstorpoollistdisk.disk | replace "," " "| trim | split " " }}
    apiVersion: openebs.io/v1alpha1
    kind: StoragePool
    metadata:
      name: {{.CstorPool.owner}}-{{ .ListItems.currentRepeatResource}}
      labels:
        cas.openebs.io/storage-pool-claim: {{.CstorPool.spc}}
        kubernetes.io/hostname: {{ .ListItems.currentRepeatResource }}
    spec:
      disks:
        diskList: {{ pluck .ListItems.currentRepeatResource .ListItems.cstorNodePoolList.nodes }}
      poolSpec:
        poolType: {{.CstorPool.poolType}}
        cacheFile: /tmp/{{.CstorPool.spc}}.cache
        overProvisioning: false
