apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana-logging
  labels:
    app: kibana-logging
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-logging
  template:
    metadata:
      labels:
        app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana-oss:6.2.2 
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
       # - name: SERVER_BASEPATH
       #   value: "/api/v1/proxy/namespaces/kube-system/services/kibana-logging"
       # - name: SERVER_NAME
       #   value: "kibana.example.org"
        ports:
        - name: ui
          containerPort: 5601
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Kibana
  name: kibana-logging
  namespace: logging
spec:
  ports:
  - nodePort: 30560
    port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana-logging
  type: NodePort
